[application]
wsURL = "ws://localhost:4546"
rpcURL = "http://localhost:4545"
timeout = 5
contractAddress = "0xA795f666ACe5cE2Bb42C70DB4775062587A08ae2"
accountContractAddress = "0x1CaFf993d5f0053156761682263c1614c7C37D7C"
nodeKeyPath = "/root/lacchain/data/key"  
nodeAddressPath = "/root/lacchain/data/nodeAddress"
